// ┌──────────────────────────────────────────────────────────────────────────┐
// │  PLACEHOLDER — Regenerate with `flutterfire configure`                   │
// │  This file is auto-generated by the FlutterFire CLI.                     │
// │  Replace the empty values below after running the CLI.                   │
// └──────────────────────────────────────────────────────────────────────────┘

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  // TODO: Replace with your actual Firebase config from `flutterfire configure`
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDQQ7ZkSRTRRXFSoGT5Zi1TGXePvimqv2g',
    appId: '1:902459921586:web:4452f5d52cdeae46ca25ab',
    messagingSenderId: '902459921586',
    projectId: 'rovdraftcoach',
    authDomain: 'rovdraftcoach.firebaseapp.com',
    storageBucket: 'rovdraftcoach.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'YOUR_API_KEY',
    appId: 'YOUR_APP_ID',
    messagingSenderId: 'YOUR_SENDER_ID',
    projectId: 'YOUR_PROJECT_ID',
    storageBucket: 'YOUR_STORAGE_BUCKET',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'YOUR_API_KEY',
    appId: 'YOUR_APP_ID',
    messagingSenderId: 'YOUR_SENDER_ID',
    projectId: 'YOUR_PROJECT_ID',
    storageBucket: 'YOUR_STORAGE_BUCKET',
    iosBundleId: 'YOUR_BUNDLE_ID',
  );
}
